MAIN_COLOUR = "#2b2b2b"
MAIN_FRAME_COLOR = "#313335"
MAIN_COLOUR_LABEL_BG = "purple"
MAIN_COLOUR_LABEL_TEXT = "white"
CANVAS_COLOUR = "lightblue"
LINE_COLOUR = "black"

COLUMNS = 25

WINDOW_WIDTH = 1900
WINDOW_HEIGHT = 1000

DATA_SITUATION = 1/5
BORDERS_SPACE = 10

DATA_FRAME_WIGHT = WINDOW_WIDTH * DATA_SITUATION - BORDERS_SPACE
DATA_FRAME_HEIGHT = WINDOW_HEIGHT - 2 * BORDERS_SPACE

CANVAS_SITUATION = 1 - DATA_SITUATION
CANVAS_WIDTH = WINDOW_WIDTH * CANVAS_SITUATION - 2 * BORDERS_SPACE
CANVAS_HEIGHT = WINDOW_HEIGHT - 2 * BORDERS_SPACE